// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VisionI.API.Infrastructure;

#nullable disable

namespace VisionI.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328100000_AddLlmAndTriage")]
    partial class AddLlmAndTriage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
                    b.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType").HasColumnType("text");
                    b.Property<string>("ClaimValue").HasColumnType("text");
                    b.Property<string>("RoleId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType").HasColumnType("text");
                    b.Property<string>("ClaimValue").HasColumnType("text");
                    b.Property<string>("UserId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider").HasColumnType("text");
                    b.Property<string>("ProviderKey").HasColumnType("text");
                    b.Property<string>("ProviderDisplayName").HasColumnType("text");
                    b.Property<string>("UserId").IsRequired().HasColumnType("text");
                    b.HasKey("LoginProvider", "ProviderKey");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId").HasColumnType("text");
                    b.Property<string>("RoleId").HasColumnType("text");
                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId").HasColumnType("text");
                    b.Property<string>("LoginProvider").HasColumnType("text");
                    b.Property<string>("Name").HasColumnType("text");
                    b.Property<string>("Value").HasColumnType("text");
                    b.HasKey("UserId", "LoginProvider", "Name");
                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VisionI.API.Models.Entities.AppUser", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<int>("AccessFailedCount").HasColumnType("integer");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("DisplayName").IsRequired().HasColumnType("text");
                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<bool>("LockoutEnabled").HasColumnType("boolean");
                    b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
                    b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("PasswordHash").HasColumnType("text");
                    b.Property<string>("PhoneNumber").HasColumnType("text");
                    b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
                    b.Property<string>("SecurityStamp").HasColumnType("text");
                    b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
                    b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VisionI.API.Models.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<string>("Action").IsRequired().HasColumnType("text");
                    b.Property<string>("Detail").HasColumnType("text");
                    b.Property<string>("IpAddress").HasColumnType("text");
                    b.Property<string>("Resource").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("Timestamp").HasColumnType("timestamp with time zone");
                    b.Property<string>("UserId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Timestamp");
                    b.HasIndex("UserId");
                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("VisionI.API.Models.Entities.EventTriageRecord", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("AnalystDisplayName").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("AnalystUserId").HasMaxLength(128).HasColumnType("character varying(128)");
                    b.Property<double?>("ConfidenceScore").HasColumnType("double precision");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("EventId").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
                    b.Property<string>("EventType").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasDefaultValue("");
                    b.Property<DateTime>("LastSeenAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Note").HasColumnType("text");
                    b.Property<string>("Priority").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasDefaultValue("medium");
                    b.Property<int>("RelatedActorCount").HasColumnType("integer").HasDefaultValue(0);
                    b.Property<string>("Region").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<double?>("RiskScore").HasColumnType("double precision");
                    b.Property<int>("SimilarEventCount").HasColumnType("integer").HasDefaultValue(0);
                    b.Property<string>("Source").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasDefaultValue("");
                    b.Property<string>("SourceUrl").HasMaxLength(1024).HasColumnType("character varying(1024)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasDefaultValue("new");
                    b.Property<string>("Title").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasDefaultValue("");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("AnalystUserId");
                    b.HasIndex("EventId").IsUnique();
                    b.HasIndex("Priority");
                    b.HasIndex("Status");
                    b.HasIndex("UpdatedAt");
                    b.ToTable("EventTriageRecords");
                });

            modelBuilder.Entity("VisionI.API.Models.Entities.LlmProviderConfig", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("BaseUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("EncryptedApiKey").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsDefault").HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<bool>("IsEnabled").HasColumnType("boolean").HasDefaultValue(true);
                    b.Property<DateTime?>("LastTestedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("LastTestMessage").HasColumnType("text");
                    b.Property<bool?>("LastTestSucceeded").HasColumnType("boolean");
                    b.Property<string>("Model").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Provider").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<string>("UpdatedByUserId").IsRequired().HasColumnType("text").HasDefaultValue("");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("IsDefault");
                    b.HasIndex("Provider");
                    b.ToTable("LlmProviderConfigs");
                });

            modelBuilder.Entity("VisionI.API.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("RevokedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Token").IsRequired().HasColumnType("text");
                    b.Property<string>("UserId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Token").IsUnique();
                    b.HasIndex("UserId");
                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VisionI.API.Models.Entities.AppUser", null)
                        .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VisionI.API.Models.Entities.AppUser", null)
                        .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("VisionI.API.Models.Entities.AppUser", null)
                        .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VisionI.API.Models.Entities.AppUser", null)
                        .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("VisionI.API.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("VisionI.API.Models.Entities.AppUser", "User")
                        .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
